version: "3"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: squid
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
  
  squid:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "4010:4010"
      - "4000:4000"
